import { Destination, NearbyFacility, AlternativeSpot } from './types';

export const INDIAN_STATES = [
  'All States',
  'Uttar Pradesh',
  'Himachal Pradesh',
  'Uttarakhand',
  'Goa',
  'Kerala',
  'Rajasthan',
  'Ladakh',
  'Jammu & Kashmir',
  'Tamil Nadu',
  'Punjab',
  'Andhra Pradesh',
  'Karnataka',
  'Maharashtra',
  'Odisha',
  'Gujarat',
  'Andaman & Nicobar',
  'Delhi',
] as const;

export const POPULAR_DESTINATIONS: Destination[] = [
  // =================== TEMPLES & SPIRITUAL ===================
  {
    id: 'kedarnath-temple',
    name: 'Kedarnath Temple',
    category: 'Temples',
    state: 'Uttarakhand',
    city: 'Rudraprayag',
    country: 'India',
    coordinates: { lat: 30.7352, lng: 79.0669 },
    image: 'https://images.unsplash.com/photo-1626014303757-6466336e3926?auto=format&fit=crop&w=1200&q=80',
    description: 'Holiest Shiva temple nestled amidst snow-capped Garhwal Himalayan peaks, one of the 12 Jyotirlingas and supreme Char Dham pilgrimage site.',
    rating: 4.9,
    reviewsCount: 165000,
    entryFee: 0,
    currency: 'INR',
    openingHours: '05:00 AM - 09:00 PM',
    typicalDurationHours: 4,
    baseCrowdFactor: 90,
    tags: ['Jyotirlinga', 'Himalayas', 'Char Dham', 'Trek', 'Spiritual Sanctuary']
  },
  {
    id: 'tirupati-balaji',
    name: 'Tirupati Balaji (Venkateswara Temple)',
    category: 'Temples',
    state: 'Andhra Pradesh',
    city: 'Tirupati',
    country: 'India',
    coordinates: { lat: 13.6833, lng: 79.3472 },
    image: 'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=1200&q=80',
    description: 'The world\'s most visited holy shrine dedicated to Lord Venkateswara atop the 7 sacred Seshachalam hills, famous for Tirupati Laddu Prasadam.',
    rating: 4.9,
    reviewsCount: 320000,
    entryFee: 300, // Special Entry Darshan
    currency: 'INR',
    openingHours: '03:00 AM - 11:00 PM',
    typicalDurationHours: 5,
    baseCrowdFactor: 95,
    tags: ['Holy Darshan', 'Tirumala Hills', 'Laddu Prasadam', 'Vedic Heritage']
  },
  {
    id: 'kashi-vishwanath',
    name: 'Kashi Vishwanath Temple',
    category: 'Temples',
    state: 'Uttar Pradesh',
    city: 'Varanasi',
    country: 'India',
    coordinates: { lat: 25.3109, lng: 83.0107 },
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80',
    description: 'Ancient golden-spired Shiva Jyotirlinga on the western bank of the sacred Ganges River, connected to the majestic newly restored Vishwanath Corridor.',
    rating: 4.8,
    reviewsCount: 180000,
    entryFee: 0,
    currency: 'INR',
    openingHours: '03:00 AM - 11:00 PM',
    typicalDurationHours: 2.5,
    baseCrowdFactor: 88,
    tags: ['Ganga Ghats', 'Jyotirlinga', 'Evening Ganga Aarti', 'Ancient Varanasi']
  },
  {
    id: 'meenakshi-temple',
    name: 'Meenakshi Amman Temple',
    category: 'Temples',
    state: 'Tamil Nadu',
    city: 'Madurai',
    country: 'India',
    coordinates: { lat: 9.9195, lng: 78.1193 },
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
    description: 'Architectural marvel of Dravidian architecture featuring 14 soaring Gopuram towers sculpted with thousands of vibrant mythological deities.',
    rating: 4.8,
    reviewsCount: 145000,
    entryFee: 50,
    currency: 'INR',
    openingHours: '05:00 AM - 12:30 PM, 04:00 PM - 09:30 PM',
    typicalDurationHours: 3,
    baseCrowdFactor: 82,
    tags: ['Dravidian Architecture', 'Sculpted Gopurams', 'Thousand Pillar Hall']
  },
  {
    id: 'golden-temple',
    name: 'Golden Temple (Harmandir Sahib)',
    category: 'Temples',
    state: 'Punjab',
    city: 'Amritsar',
    country: 'India',
    coordinates: { lat: 31.6200, lng: 74.8765 },
    image: 'https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?auto=format&fit=crop&w=1200&q=80',
    description: 'Spiritual epicenter of Sikhism plated with pure gold, surrounded by the Amrit Sarovar holy lake and serving the world\'s largest free community kitchen (Langar).',
    rating: 4.9,
    reviewsCount: 220000,
    entryFee: 0,
    currency: 'INR',
    openingHours: 'Open 24 Hours',
    typicalDurationHours: 2.5,
    baseCrowdFactor: 85,
    tags: ['Golden Glow', 'Free Langar', 'Holy Amrit Sarovar', 'Serenity']
  },

  // =================== BEACHES ===================
  {
    id: 'baga-beach',
    name: 'Baga & Calangute Beach',
    category: 'Beaches',
    state: 'Goa',
    city: 'North Goa',
    country: 'India',
    coordinates: { lat: 15.5553, lng: 73.7517 },
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
    description: 'The liveliest shoreline in North Goa, celebrated for high-octane water sports (parasailing, jet-ski), beachfront shacks, seafood, and legendary nightlife.',
    rating: 4.5,
    reviewsCount: 195000,
    entryFee: 0,
    currency: 'INR',
    openingHours: 'Open 24 Hours',
    typicalDurationHours: 4,
    baseCrowdFactor: 88,
    tags: ['Water Sports', 'Nightlife', 'Seafood Shacks', 'Golden Sand']
  },
  {
    id: 'radhanagar-beach',
    name: 'Radhanagar Beach (Beach No. 7)',
    category: 'Beaches',
    state: 'Andaman & Nicobar',
    city: 'Havelock Island',
    country: 'India',
    coordinates: { lat: 11.9840, lng: 92.9515 },
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    description: 'Crowned Asia\'s best beach by Time Magazine, celebrated for pristine turquoise waters, powdery white sands, and dramatic sunset rainforest reflections.',
    rating: 4.9,
    reviewsCount: 68000,
    entryFee: 0,
    currency: 'INR',
    openingHours: '06:00 AM - 05:30 PM',
    typicalDurationHours: 3.5,
    baseCrowdFactor: 55,
    tags: ['Pristine Paradise', 'Turquoise Waters', 'Sunset Views', 'White Sand']
  },
  {
    id: 'kovalam-beach',
    name: 'Kovalam Lighthouse Beach',
    category: 'Beaches',
    state: 'Kerala',
    city: 'Thiruvananthapuram',
    country: 'India',
    coordinates: { lat: 8.3988, lng: 76.9787 },
    image: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&w=1200&q=80',
    description: 'Crescent-shaped tropical coastline backed by swaying coconut palms, featuring the 35-meter Vizhinjam Lighthouse with panoramic Arabian Sea views.',
    rating: 4.6,
    reviewsCount: 88000,
    entryFee: 20, // Lighthouse entry
    currency: 'INR',
    openingHours: 'Open 24 Hours (Lighthouse: 10 AM - 5 PM)',
    typicalDurationHours: 3,
    baseCrowdFactor: 72,
    tags: ['Iconic Lighthouse', 'Ayurvedic Massage', 'Surfing', 'Sunset Promenade']
  },
  {
    id: 'varkala-beach',
    name: 'Varkala Cliff Beach (Papanasam)',
    category: 'Beaches',
    state: 'Kerala',
    city: 'Varkala',
    country: 'India',
    coordinates: { lat: 8.7379, lng: 76.7032 },
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    description: 'Unique geological red laterite cliffs adjacent to the Arabian Sea, dotted with boho cliff-top cafes, yoga retreats, and holy cleansing spring waters.',
    rating: 4.7,
    reviewsCount: 76000,
    entryFee: 0,
    currency: 'INR',
    openingHours: 'Open 24 Hours',
    typicalDurationHours: 3,
    baseCrowdFactor: 65,
    tags: ['Red Cliffs', 'Boho Cafes', 'Sunset Point', 'Yoga Retreats']
  },

  // =================== MOUNTAINS & HILL STATIONS ===================
  {
    id: 'rohtang-pass',
    name: 'Rohtang Pass & Solang Valley',
    category: 'Mountains',
    state: 'Himachal Pradesh',
    city: 'Manali',
    country: 'India',
    coordinates: { lat: 32.3716, lng: 77.2466 },
    image: 'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?auto=format&fit=crop&w=1200&q=80',
    description: 'High mountain pass at 13,058 feet on the Pir Panjal Range connecting Kullu with Lahaul-Spiti, world-famous for year-round snow sports and breathtaking vistas.',
    rating: 4.8,
    reviewsCount: 172000,
    entryFee: 550, // NGT green permit
    currency: 'INR',
    openingHours: '06:00 AM - 04:00 PM (Closed on Tuesdays)',
    typicalDurationHours: 5,
    baseCrowdFactor: 92,
    tags: ['Snow Point', 'Himalayan Pass', 'Paragliding', 'Zorbing', 'Atal Tunnel']
  },
  {
    id: 'pangong-lake',
    name: 'Pangong Tso Lake',
    category: 'Mountains',
    state: 'Ladakh',
    city: 'Leh Ladakh',
    country: 'India',
    coordinates: { lat: 33.7595, lng: 78.6674 },
    image: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80',
    description: 'High-altitude endorheic saline lake at 14,270 feet that changes shades from vivid turquoise to cobalt blue, framed by barren, snow-dusted mountains.',
    rating: 4.9,
    reviewsCount: 110000,
    entryFee: 20,
    currency: 'INR',
    openingHours: 'Open 24 Hours',
    typicalDurationHours: 4,
    baseCrowdFactor: 60,
    tags: ['Color-Changing Waters', 'High Altitude', 'Star Gazing', '3 Idiots Point']
  },
  {
    id: 'gulmarg-gondola',
    name: 'Gulmarg Gondola & Apharwat Peak',
    category: 'Mountains',
    state: 'Jammu & Kashmir',
    city: 'Gulmarg',
    country: 'India',
    coordinates: { lat: 34.0484, lng: 74.3805 },
    image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80',
    description: 'The world\'s second highest operating cable car rising to 13,780 feet, delivering world-class ski powder, pine forest sweeps, and views of Nanga Parbat.',
    rating: 4.8,
    reviewsCount: 135000,
    entryFee: 950, // Phase 1 ticket
    currency: 'INR',
    openingHours: '09:00 AM - 05:00 PM',
    typicalDurationHours: 4,
    baseCrowdFactor: 89,
    tags: ['Highest Gondola', 'Ski Resort', 'Snow Peaks', 'Pine Valleys']
  },
  {
    id: 'munnar-tea-hills',
    name: 'Munnar Tea Estates & Anamudi',
    category: 'Mountains',
    state: 'Kerala',
    city: 'Munnar',
    country: 'India',
    coordinates: { lat: 10.0889, lng: 77.0595 },
    image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=80',
    description: 'Misty rolling hills covered in emerald-green carpeted tea plantations at the confluence of 3 mountain streams, home to the endangered Nilgiri Tahr.',
    rating: 4.7,
    reviewsCount: 142000,
    entryFee: 150, // Eravikulam National Park
    currency: 'INR',
    openingHours: '07:30 AM - 04:00 PM',
    typicalDurationHours: 3.5,
    baseCrowdFactor: 75,
    tags: ['Tea Gardens', 'Misty Valleys', 'Nilgiri Tahr', 'Trekking']
  },

  // =================== HERITAGE & ROYAL MONUMENTS ===================
  {
    id: 'taj-mahal',
    name: 'Taj Mahal',
    category: 'Heritage',
    state: 'Uttar Pradesh',
    city: 'Agra',
    country: 'India',
    coordinates: { lat: 27.1751, lng: 78.0421 },
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80',
    description: 'Iconic 17th-century white marble mausoleum built by Mughal emperor Shah Jahan, UNESCO World Heritage site and one of the New 7 Wonders of the World.',
    rating: 4.8,
    reviewsCount: 142800,
    entryFee: 50,
    currency: 'INR',
    openingHours: '06:00 AM - 06:30 PM (Closed on Fridays)',
    typicalDurationHours: 2.5,
    baseCrowdFactor: 85,
    tags: ['Mughal Architecture', 'Wonders of World', 'Photography', 'Historic Monument']
  },
  {
    id: 'hawa-mahal',
    name: 'Hawa Mahal & City Palace',
    category: 'Heritage',
    state: 'Rajasthan',
    city: 'Jaipur',
    country: 'India',
    coordinates: { lat: 26.9239, lng: 75.8267 },
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
    description: 'Striking 5-story pink-painted sandstone palace with 953 honeycomb jharokha windows designed for royal ladies to view royal processions.',
    rating: 4.6,
    reviewsCount: 98000,
    entryFee: 50,
    currency: 'INR',
    openingHours: '09:00 AM - 05:00 PM',
    typicalDurationHours: 2,
    baseCrowdFactor: 78,
    tags: ['Pink City', 'Royal Rajput', 'Instagrammable', 'Heritage']
  },
  {
    id: 'amer-fort',
    name: 'Amer Fort (Amber Palace)',
    category: 'Heritage',
    state: 'Rajasthan',
    city: 'Jaipur',
    country: 'India',
    coordinates: { lat: 26.9855, lng: 75.8513 },
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
    description: 'Colossal hilltop fortress overlooking Maota Lake, famous for Sheesh Mahal (Mirror Palace), Diwan-e-Aam, and elephant pathways.',
    rating: 4.7,
    reviewsCount: 115000,
    entryFee: 100,
    currency: 'INR',
    openingHours: '08:00 AM - 05:30 PM, 06:30 PM - 09:15 PM',
    typicalDurationHours: 3,
    baseCrowdFactor: 80,
    tags: ['Hill Fort', 'Sheesh Mahal', 'Light Show', 'UNESCO']
  },
  {
    id: 'red-fort',
    name: 'Red Fort (Lal Qila)',
    category: 'Heritage',
    state: 'Delhi',
    city: 'New Delhi',
    country: 'India',
    coordinates: { lat: 28.6562, lng: 77.2410 },
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1200&q=80',
    description: 'Massive red sandstone fortress serving as the imperial seat of the Mughal dynasty for nearly 200 years, hosting the annual Independence Day address.',
    rating: 4.5,
    reviewsCount: 88400,
    entryFee: 35,
    currency: 'INR',
    openingHours: '09:30 AM - 04:30 PM (Closed on Mondays)',
    typicalDurationHours: 2,
    baseCrowdFactor: 75,
    tags: ['Delhi Heritage', 'Sound & Light Show', 'Mughal Citadel']
  },
  {
    id: 'mysore-palace',
    name: 'Mysore Palace (Amba Vilas)',
    category: 'Heritage',
    state: 'Karnataka',
    city: 'Mysuru',
    country: 'India',
    coordinates: { lat: 12.3051, lng: 76.6551 },
    image: 'https://images.unsplash.com/photo-1600100397608-f010f443b745?auto=format&fit=crop&w=1200&q=80',
    description: 'Historical palace residence of the Wadiyar dynasty, stunning Indo-Saracenic masterpiece illuminated by nearly 100,000 bulbs every weekend.',
    rating: 4.7,
    reviewsCount: 128000,
    entryFee: 70,
    currency: 'INR',
    openingHours: '10:00 AM - 05:30 PM',
    typicalDurationHours: 2.5,
    baseCrowdFactor: 84,
    tags: ['Grand Illumination', 'Wadiyar Royalty', 'Dasara Festival', 'Architecture']
  }
];

export const FALLBACK_FACILITIES: Record<string, NearbyFacility[]> = {
  'default': [
    { id: 'df1', name: 'Designated Visitor Parking P1 & P2', type: 'parking', distanceMeters: 350, vicinity: 'Main Entry Boulevard', statusText: 'Open (Available parking slots)', isOpenNow: true },
    { id: 'df2', name: 'Clean Public Restroom Complex', type: 'restroom', distanceMeters: 150, vicinity: 'Visitor Reception Area', statusText: 'Free access & sanitized', isOpenNow: true },
    { id: 'df3', name: 'Heritage Courtyard Cafe & Refreshment Stalls', type: 'food', distanceMeters: 280, rating: 4.4, vicinity: 'Promenade Plaza', statusText: 'Open (Snacks, water, hot meals)', isOpenNow: true },
    { id: 'df4', name: 'Red Cross First Aid Post & Defibrillator', type: 'medical', distanceMeters: 200, vicinity: 'Main Security Checkpoint', statusText: 'Staffed & active', isOpenNow: true },
  ]
};

export const FALLBACK_ALTERNATIVES: Record<string, AlternativeSpot[]> = {
  'taj-mahal': [
    {
      id: 'alt-1',
      name: 'Mehtab Bagh (Moonlight Garden)',
      category: 'Gardens & Sunset View',
      crowdScore: 28,
      crowdDifferencePercent: 65,
      distanceKm: 2.1,
      image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=600&q=80',
      description: 'Charbagh complex perfectly aligned across the Yamuna River, offering direct, peaceful sunset views of the Taj Mahal with virtually no crowds.',
      rating: 4.6,
      whyVisit: 'Sunset photography without security lines, serene river breezes.'
    },
    {
      id: 'alt-2',
      name: 'Tomb of I\'timad-ud-Daulah (Baby Taj)',
      category: 'Mughal Architecture',
      crowdScore: 32,
      crowdDifferencePercent: 58,
      distanceKm: 4.8,
      image: 'https://images.unsplash.com/photo-1585139097723-5e9275ce30d9?auto=format&fit=crop&w=600&q=80',
      description: 'Often regarded as the draft for the Taj Mahal, featuring delicate pietra dura inlay work and tranquil riverside gardens.',
      rating: 4.5,
      whyVisit: 'Exquisite craftsmanship with under 15 minute wait times.'
    }
  ],
  'default': [
    {
      id: 'alt-def-1',
      name: 'Scenic Hilltop Viewpoint & Heritage Trail',
      category: 'Nature & Solitude',
      crowdScore: 25,
      crowdDifferencePercent: 60,
      distanceKm: 3.4,
      image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=600&q=80',
      description: 'Quiet elevated viewpoint with panoramic vistas, shaded paths, and serene atmosphere.',
      rating: 4.6,
      whyVisit: 'Zero queue entry, fresh mountain breeze, peaceful walkways.'
    },
    {
      id: 'alt-def-2',
      name: 'Ancient Riverside Ghat & Botanical Garden',
      category: 'Culture & Nature',
      crowdScore: 30,
      crowdDifferencePercent: 50,
      distanceKm: 4.5,
      image: 'https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=600&q=80',
      description: 'Spiritual riverside steps with clean bathing areas and quiet meditation gardens.',
      rating: 4.5,
      whyVisit: 'Peaceful prayer and reflection away from peak crowds.'
    }
  ]
};
